import fs from "node:fs";
import path from "node:path";
import { brand } from "./brand.ts";
import { root } from "./paths.ts";
import { kebab, loadSpecs, type ComponentSpec } from "./specs.ts";

// Builds docs/accessibility-audit.md from each spec's a11y section, so the
// manual audit always matches what the components promise.

export const auditFile = path.join(root, "docs", "accessibility-audit.md");

/** Where each component lives in the playground (apps/playground/src/app.tsx). */
const playgroundSection: Record<string, string> = {
  Button: "Button",
  TextField: "TextField",
  Checkbox: "Checkbox, Switch, RadioGroup",
  Switch: "Checkbox, Switch, RadioGroup",
  RadioGroup: "Checkbox, Switch, RadioGroup",
  Select: "Select",
  Tabs: "Tabs",
  Dialog: "Overlays (Delete project)",
  Popover: "Overlays (Filters)",
  Tooltip: "Overlays (the ⚙ button)",
  Toast: "Overlays (Delete project → Delete, or Show error toast)",
  Calendar: "Dates (the standalone calendar)",
  DatePicker: "Dates (Due date)",
  DateRangePicker: "Dates (Report period)",
  Combobox: "Combobox (Country, Markets, Assignee, Product)",
  DataGrid: "Data grid (100,000 orders) and Data grid: editing and pagination",
};

const SETUPS = ["NVDA + Chrome (Windows)", "VoiceOver + Safari (macOS)", "VoiceOver + Safari (iOS)", "TalkBack + Chrome (Android)"];
const SHORT = ["NVDA", "VO mac", "VO iOS", "TalkBack"];

// Spec text like "Remove <option>" would otherwise be swallowed as an HTML tag.
const md = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const cell = (s: string) => md(s.length > 64 ? `${s.slice(0, 61)}…` : s).replace(/\|/g, "\\|");

function componentSection(spec: ComponentSpec): string {
  const a = spec.a11y;
  // Older components are all on the playground page; every component also has
  // a docs page with its examples (npm run docs).
  const where = playgroundSection[spec.name]
    ? `playground: **${playgroundSection[spec.name]}**`
    : `docs site: **http://localhost:5190/components/${kebab(spec.name)}**`;
  const groups: Array<[string, string[]]> = [
    ["What you should hear", a.screenReader ?? []],
    ["Keyboard, with the screen reader running (in NVDA, focus mode: NVDA+Space switches)", a.keyboard],
    ["Requirements", a.requirements ?? []],
  ];

  // One number per check across all groups, so each table row maps to one item.
  let n = 0;
  const numbered = groups.map(([title, items]) => ({ title, items: items.map((text) => ({ n: ++n, text })) }));
  const all = numbered.flatMap((g) => g.items);

  return [
    `### ${spec.name}`,
    "",
    `Role \`${a.role}\` · WCAG ${a.wcag} · spec: [\`specs/${kebab(spec.name)}.spec.json\`](../specs/${kebab(spec.name)}.spec.json) · ${where}`,
    "",
    ...numbered.flatMap((g) =>
      g.items.length ? [`**${g.title}**`, "", ...g.items.map((i) => `${i.n}. ${md(i.text)}`), ""] : [],
    ),
    "| # | Check | " + SHORT.join(" | ") + " | Notes |",
    "|---|---|" + SHORT.map(() => "---").join("|") + "|---|",
    ...all.map((i) => `| ${i.n} | ${cell(i.text)} |${SHORT.map(() => " ").join("|")}| |`),
    "",
  ].join("\n");
}

export function buildAudit(): string[] {
  const specs = loadSpecs().map((s) => s.spec);
  const total = specs.reduce((n, s) => n + (s.a11y.screenReader?.length ?? 0) + s.a11y.keyboard.length + (s.a11y.requirements?.length ?? 0), 0);

  const doc = `# Screen reader audit

<!-- Generated by \`npm run gen\` from specs/*.spec.json (a11y section). Edit the specs, not this file. -->

A manual check of every ${brand.displayName} component with real screen readers: ${specs.length} components, ${total} checks. Automated tests already cover roles, names, ARIA states, focus handling and color contrast (axe-core and the component tests), but they can't hear what a screen reader actually says, or tell whether it makes sense. That's what this audit is for.

## Before you start

**Screen readers.** Before launch, test at least the first two. The mobile ones are needed before 1.0.

| Setup | Get it | Basics |
|---|---|---|
| ${SETUPS[0]} | Free from [nvaccess.org](https://www.nvaccess.org/) | Modifier is Insert (or Caps Lock). NVDA+Space toggles browse and focus mode. Tab and arrow keys move; NVDA+T reads the page title. |
| ${SETUPS[1]} | Built in: Cmd+F5 | Modifier is Ctrl+Option (VO). VO+Right moves; VO+U opens the rotor; VO+Space activates. |
| ${SETUPS[2]} | Settings → Accessibility → VoiceOver | Swipe right/left to move, double-tap to activate, rotor with a two-finger twist. |
| ${SETUPS[3]} | Settings → Accessibility → TalkBack | Swipe right/left to move, double-tap to activate. |

**The playground and docs site.** Run \`npm run dev\` and open http://localhost:5173 for the playground; newer components are on the docs site instead (\`npm run docs\`, http://localhost:5190). Each component below says where. For phones on the same network, run \`npx vite apps/playground --host\` and open the address it prints. Test in light and dark mode, and at 200% browser zoom at least once.

**Turn the mouse off.** Do everything with the keyboard, or touch gestures on mobile. If a step only works with a mouse, that's a failure.

## How to record results

For each check, write **pass**, **fail**, or **n/a** in the table under the component, one column per setup, and note what you heard in *Notes*.

- **Wording differs between screen readers.** "Button" vs "push button" is fine. Fail a check only if information is **missing, wrong, or misleading**, or you can't complete the task.
- **Severity for failures:**
  - **Blocker:** you can't complete the task.
  - **Major:** you can finish, but only with difficulty, or you get wrong information.
  - **Minor:** it's verbose, repetitive or oddly worded.
- File each failure as a GitHub issue titled \`[a11y] <Component>: <what went wrong>\`, with the setup, the steps, what you heard and what you expected.
- Fixes go into the component *and* its spec, so the checklist and tests change with them.

## Check these first

Development turned up these risks, which automated tests couldn't settle:

1. **Focus returning after a Dialog or Popover closes.** React Aria restores focus one animation frame later. Tests confirm it, but check that the screen reader actually announces the trigger again.
2. **Combobox tags while the list is open.** React Aria hides everything outside the list, including the tags, from screen readers while it's open. Check that this isn't confusing, and that the tags come back when it closes.
3. **Combobox load-more (Assignee).** Loading more with the mouse and with Arrow Down is tested in Chromium (tests/visual/interactions.spec.ts). Check what screen readers say while it loads: the loading row should be read as \"Loading more…\", and the new count should be announced once results arrive.
4. **Data Grid with 100,000 rows.** Row numbers should come from the full dataset even though only ~20 rows exist in the page. Also check NVDA's table commands (Ctrl+Alt+Arrow keys) in browse mode: the grid is built from \`div\`s with ARIA roles, not a \`<table>\`.
5. **Data Grid editing on phones.** A second tap on the selected cell opens the editor (tested with touch emulation). With TalkBack and VoiceOver on iOS, gestures differ: check that double-tapping an editable cell opens an editor announced as "Edit <column>", and that the keyboard appears.
6. **Date segments.** Listen to how each segment is announced (month, day, year) in the start and end fields of the range picker.
7. **Toast.** It's built on React Aria's toast API, which is still marked unstable. Check that announcements happen, and happen only once.

## Results summary

Fill this in as you go: ✅ all pass · ⚠️ minor issues · ❌ major or blocker.

| Component | ${SHORT.join(" | ")} |
|---|${SHORT.map(() => "---").join("|")}|
${specs.map((s) => `| [${s.name}](#${s.name.toLowerCase()}) |${SHORT.map(() => " ").join("|")}|`).join("\n")}

## Components

${specs.map(componentSection).join("\n")}`;

  fs.mkdirSync(path.dirname(auditFile), { recursive: true });
  fs.writeFileSync(auditFile, doc);
  return [auditFile];
}
