import fs from "node:fs";
import path from "node:path";
import { brand } from "./brand.ts";
import { tokensDir, tokensOutDir } from "./paths.ts";

type Tree = Record<string, unknown>;

export interface FlatToken {
  path: string; // dot path, e.g. "color.action.primary"
  type: string;
  value: string; // raw value, may be a {reference}
}

const REF = /^\{([^}]+)\}$/;

function readTree(file: string): Tree {
  return JSON.parse(fs.readFileSync(path.join(tokensDir, file), "utf8"));
}

/** Flattens a DTCG tree, inheriting $type from parent groups. */
export function flatten(tree: Tree, prefix: string[] = [], inheritedType?: string): FlatToken[] {
  const type = (tree.$type as string | undefined) ?? inheritedType;
  if ("$value" in tree) {
    return [{ path: prefix.join("."), type: type ?? "unknown", value: String(tree.$value) }];
  }
  return Object.entries(tree)
    .filter(([key]) => !key.startsWith("$"))
    .flatMap(([key, child]) => flatten(child as Tree, [...prefix, key], type));
}

function resolve(value: string, all: Map<string, FlatToken>, seen: string[] = []): string {
  const match = value.match(REF);
  if (!match) return value;
  const target = match[1];
  if (seen.includes(target)) throw new Error(`Circular token reference: ${[...seen, target].join(" -> ")}`);
  const token = all.get(target);
  if (!token) throw new Error(`Unknown token reference {${target}}`);
  return resolve(token.value, all, [...seen, target]);
}

export const cssVar = (tokenPath: string) => `--${brand.cssPrefix}-${tokenPath.replace(/\./g, "-")}`;

export interface TokenSet {
  core: FlatToken[];
  light: FlatToken[];
  dark: FlatToken[];
  compact: FlatToken[];
}

export function loadTokens(): TokenSet {
  return {
    core: flatten(readTree("core.tokens.json")),
    light: flatten(readTree("semantic.light.tokens.json")),
    dark: flatten(readTree("semantic.dark.tokens.json")),
    compact: flatten(readTree("density.compact.tokens.json")),
  };
}

/** All semantic token paths. Light is the complete set; dark overrides a subset. */
export function semanticPaths(set: TokenSet): Set<string> {
  return new Set(set.light.map((t) => t.path));
}

function resolveMode(set: TokenSet, mode: FlatToken[]): FlatToken[] {
  const all = new Map([...set.core, ...set.light, ...mode].map((t) => [t.path, t]));
  return mode.map((t) => ({ ...t, value: resolve(t.value, all) }));
}

function block(selector: string, tokens: FlatToken[], indent = ""): string {
  const lines = tokens.map((t) => `${indent}  ${cssVar(t.path)}: ${t.value};`);
  return `${indent}${selector} {\n${lines.join("\n")}\n${indent}}`;
}

const toRecord = (tokens: FlatToken[]) =>
  Object.fromEntries(tokens.map((t) => [t.path, { type: t.type, value: t.value }]));

export function buildTokens(): string[] {
  const set = loadTokens();
  const lightPaths = semanticPaths(set);
  for (const t of set.dark) {
    if (!lightPaths.has(t.path)) throw new Error(`Dark token ${t.path} has no light counterpart`);
  }

  const core = resolveMode(set, set.core);
  const light = resolveMode(set, set.light);
  const dark = resolveMode(set, set.dark);
  const compact = resolveMode(set, set.compact);
  for (const t of set.compact) {
    if (!lightPaths.has(t.path)) throw new Error(`Compact density token ${t.path} has no default counterpart`);
  }

  const css = [
    `/* Generated by ${brand.name} codegen. Do not edit; change /tokens instead. */`,
    block(":root", [...core, ...light]),
    `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme="light"])', dark, "  ")}\n}`,
    block(':root[data-theme="dark"]', dark),
    // Density: put data-density="compact" on <html> or on any container to tighten everything inside it.
    block('[data-density="compact"]', compact),
    "",
  ].join("\n\n");

  // Flat JSON feeds the Figma plugin and the MCP server later.
  const json = { core: toRecord(core), modes: { light: toRecord(light), dark: toRecord(dark) } };

  fs.mkdirSync(tokensOutDir, { recursive: true });
  const cssFile = path.join(tokensOutDir, "tokens.css");
  const jsonFile = path.join(tokensOutDir, "tokens.json");
  fs.writeFileSync(cssFile, css);
  fs.writeFileSync(jsonFile, JSON.stringify(json, null, 2) + "\n");
  return [cssFile, jsonFile];
}
