import fs from "node:fs";
import path from "node:path";
import { brand } from "./brand.ts";
import { reactGeneratedDir } from "./paths.ts";
import { kebab, loadSpecs, type ComponentSpec, type PropSpec } from "./specs.ts";

function tsType(prop: PropSpec): string {
  switch (prop.type) {
    case "enum":
      return prop.values!.map((v) => JSON.stringify(v)).join(" | ");
    case "node":
      return "ReactNode";
    case "callback":
    case "custom":
      return prop.tsType!;
    default:
      return prop.type;
  }
}

function jsDoc(prop: PropSpec): string {
  const lines = [prop.description];
  if (prop.default !== undefined) lines.push(`@default ${JSON.stringify(prop.default)}`);
  return `  /**\n${lines.map((l) => `   * ${l}`).join("\n")}\n   */`;
}

const camel = (name: string) => name[0].toLowerCase() + name.slice(1);

export function renderTypes(spec: ComponentSpec): string {
  const props = Object.entries(spec.props);
  const needsReactNode = props.some(([, p]) => p.type === "node" || /\bReactNode\b/.test(p.tsType ?? ""));
  const defaults = props.filter(([, p]) => p.default !== undefined);
  const enums = props.filter(([, p]) => p.type === "enum");
  const id = camel(spec.name);

  const out = [
    `// Generated by ${brand.name} codegen from specs/${kebab(spec.name)}.spec.json (v${spec.version}).`,
    `// Do not edit. Change the spec and run \`npm run gen\`.`,
    "",
  ];
  if (needsReactNode) out.push(`import type { ReactNode } from "react";`, "");

  for (const [name, p] of enums) {
    out.push(`export const ${id}${name[0].toUpperCase()}${name.slice(1)}Values = [${p.values!.map((v) => JSON.stringify(v)).join(", ")}] as const;`);
  }
  if (enums.length) out.push("");

  out.push(`/** ${spec.description} */`, `export interface ${spec.name}SpecProps {`);
  for (const [name, p] of props) {
    out.push(jsDoc(p), `  ${name}${p.required ? "" : "?"}: ${tsType(p)};`);
  }
  out.push("}", "");

  out.push(`export const ${id}Defaults = {`);
  for (const [name, p] of defaults) out.push(`  ${name}: ${JSON.stringify(p.default)},`);
  out.push("} as const;", "");

  out.push(
    `export const ${id}Meta = ${JSON.stringify(
      { name: spec.name, version: spec.version, status: spec.status ?? "experimental", role: spec.a11y.role },
      null,
      2,
    )} as const;`,
    "",
  );
  return out.join("\n");
}

export function buildTypes(): string[] {
  fs.mkdirSync(reactGeneratedDir, { recursive: true });
  const written = loadSpecs().map(({ spec }) => {
    const file = path.join(reactGeneratedDir, `${kebab(spec.name)}.types.ts`);
    fs.writeFileSync(file, renderTypes(spec));
    return file;
  });
  return written;
}
