// What the MCP tools answer, as plain functions over the context bundle
// (context.json, generated by `npm run gen`). server.ts only wires these up.

export interface PropSpec {
  type: string;
  description: string;
  values?: string[];
  default?: unknown;
  required?: boolean;
  tsType?: string;
}

export interface Spec {
  name: string;
  version: string;
  category: string;
  status?: string;
  description: string;
  props: Record<string, PropSpec>;
  variants?: string[];
  states?: string[];
  slots?: string[];
  tokens?: string[];
  a11y: { role: string; keyboard: string[]; requirements?: string[]; screenReader?: string[]; wcag: string };
  usage: { use_when: string[]; avoid_when: string[]; anti_patterns?: string[] };
  contract?: { data: string; dataStates: string[]; permissions: string[]; events: string[]; customization: string[] };
  examples?: string[];
}

export interface SourceFile {
  path: string;
  content: string;
}

export interface Component {
  id: string;
  spec: Spec;
  install: { command: string; dependencies: string[]; registryDependencies: string[] };
  examples: Array<{ name: string; code: string }>;
  files: SourceFile[];
}

export interface Token {
  path: string;
  cssVar: string;
  type: string;
  light: string;
  dark: string;
}

export interface Context {
  brand: { name: string; displayName: string; cssPrefix: string };
  components: Component[];
  tokens: Token[];
  shared: Array<{ name: string; files: SourceFile[] }>;
}

export class ToolError extends Error {}

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

export function findComponent(ctx: Context, name: string): Component {
  const key = normalize(name);
  const found = ctx.components.find((c) => normalize(c.id) === key || normalize(c.spec.name) === key);
  if (!found) {
    throw new ToolError(`No component "${name}". Available: ${ctx.components.map((c) => c.spec.name).join(", ")}`);
  }
  return found;
}

/** The file a user imports from, and what it exports. */
function entry(c: Component) {
  const file = c.files.find((f) => !f.path.startsWith("generated/")) ?? c.files[0];
  const exports = [...file.content.matchAll(/^export (?:function|const|class) (\w+)/gm)].map((m) => m[1]);
  const types = [...file.content.matchAll(/^export (?:type|interface) (\w+)/gm)].map((m) => m[1]);
  return { file: file.path.replace(/\.tsx?$/, ""), exports, types };
}

const bullets = (items: string[] | undefined) => (items ?? []).map((i) => `- ${i}`).join("\n");
const escapeCell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function propType(p: PropSpec): string {
  if (p.type === "enum") return (p.values ?? []).map((v) => `"${v}"`).join(" \\| ");
  return p.tsType ? escapeCell(p.tsType) : p.type;
}

// ---- list_components ------------------------------------------------------

export function listComponents(ctx: Context, query?: string): string {
  let items = ctx.components;
  if (query?.trim()) {
    const words = query.toLowerCase().split(/\s+/).filter(Boolean);
    const score = (c: Component) => {
      const s = c.spec;
      const name = `${s.name} ${c.id} ${s.category}`.toLowerCase();
      const text = [s.description, ...s.usage.use_when].join(" ").toLowerCase();
      return words.reduce((n, w) => n + (name.includes(w) ? 3 : 0) + (text.includes(w) ? 1 : 0), 0);
    };
    items = items
      .map((c) => ({ c, n: score(c) }))
      .filter((x) => x.n > 0)
      .sort((a, b) => b.n - a.n)
      .map((x) => x.c);
    if (!items.length) return `No components match "${query}". Call list_components without a query to see all ${ctx.components.length}.`;
  }
  const rows = items.map((c) => `| ${c.spec.name} | \`${c.id}\` | ${c.spec.category} | ${c.spec.status ?? ""} | ${escapeCell(c.spec.description)} |`);
  return [
    `${ctx.brand.displayName} components${query ? ` matching "${query}"` : ""}. Call get_component for props, accessibility and usage rules.`,
    "",
    "| Component | id | Category | Status | Description |",
    "|---|---|---|---|---|",
    ...rows,
  ].join("\n");
}

// ---- get_component --------------------------------------------------------

export function getComponent(ctx: Context, name: string): string {
  const c = findComponent(ctx, name);
  const s = c.spec;
  const e = entry(c);
  const props = Object.entries(s.props).map(
    ([n, p]) =>
      `| \`${n}\`${p.required ? " (required)" : ""} | ${propType(p)} | ${p.default === undefined ? "" : `\`${JSON.stringify(p.default)}\``} | ${escapeCell(p.description)} |`,
  );

  const sections: Array<[string, string]> = [
    [
      "Install",
      [
        `\`${c.install.command}\` copies the source into the project (the user owns it; edit it freely, \`npx ${ctx.brand.name} upgrade\` merges later changes).`,
        c.install.dependencies.length ? `npm packages: ${c.install.dependencies.map((d) => `\`${d}\``).join(", ")}` : "",
        `Also installs: ${c.install.registryDependencies.join(", ")}`,
      ]
        .filter(Boolean)
        .join("\n"),
    ],
    [
      "Import",
      [
        "```tsx",
        `import { ${e.exports.join(", ")} } from "<componentsDir>/${e.file}";`,
        "```",
        `\`componentsDir\` is set in rdloom.json (default \`src/components/rdloom\`).${e.types.length ? ` Types: ${e.types.join(", ")}.` : ""}`,
      ].join("\n"),
    ],
    ["Props", props.length ? ["The props defined by the spec. Components also accept the underlying React Aria props.", "", "| Prop | Type | Default | Description |", "|---|---|---|---|", ...props].join("\n") : ""],
    ["Variants and states", [s.variants?.length ? `Variants: ${s.variants.join(", ")}` : "", s.states?.length ? `States: ${s.states.join(", ")}` : "", s.slots?.length ? `Slots: ${s.slots.join(", ")}` : ""].filter(Boolean).join("\n")],
    [
      "Block contract",
      s.contract
        ? [
            `Data: ${s.contract.data}`,
            `Data states it handles: ${s.contract.dataStates.length ? s.contract.dataStates.join(", ") : "none (it shows what it is given)"}`,
            `Actions it asks permission for: ${s.contract.permissions.length ? s.contract.permissions.join(", ") : "none yet"}`,
            `Events (callback props): ${s.contract.events.length ? s.contract.events.join(", ") : "none"}`,
            `What you can replace or restyle: ${s.contract.customization.join("; ")}`,
          ].join("\n")
        : "",
    ],
    ["Use when", bullets(s.usage.use_when)],
    ["Avoid when", bullets(s.usage.avoid_when)],
    ["Anti-patterns (don't generate these)", bullets(s.usage.anti_patterns)],
    [
      "Accessibility",
      [
        `Role \`${s.a11y.role}\`, WCAG ${s.a11y.wcag}.`,
        s.a11y.requirements?.length ? `\nRequirements for the code you write:\n${bullets(s.a11y.requirements)}` : "",
        `\nKeyboard:\n${bullets(s.a11y.keyboard)}`,
        s.a11y.screenReader?.length ? `\nScreen readers announce:\n${bullets(s.a11y.screenReader)}` : "",
      ].join("\n"),
    ],
    ["Tokens used", (s.tokens ?? []).map((t) => `\`${t}\``).join(", ")],
    [
      "Examples",
      c.examples.length
        ? [
            `Working code for: ${c.examples.map((e) => `\`${e.name}\``).join(", ")}. Call get_example for any of them. The first one:`,
            "",
            "```tsx",
            c.examples[0].code.trimEnd(),
            "```",
            "",
            'Examples import from "@rdloom/react"; in a project that used `rdloom add`, import from the copied files instead (see Import).',
          ].join("\n")
        : "",
    ],
  ];

  return [
    `# ${s.name} (\`${c.id}\`, v${s.version}${s.status ? `, ${s.status}` : ""})`,
    "",
    s.description,
    "",
    ...sections.filter(([, body]) => body.trim()).flatMap(([title, body]) => [`## ${title}`, "", body, ""]),
  ].join("\n");
}

// ---- get_example ----------------------------------------------------------

export function getExample(ctx: Context, name: string, example?: string): string {
  const c = findComponent(ctx, name);
  const show = (e: { name: string; code: string }) => `### ${c.spec.name}: ${e.name}\n\n\`\`\`tsx\n${e.code.trimEnd()}\n\`\`\``;
  if (!example) return c.examples.map(show).join("\n\n");
  const e = c.examples.find((x) => x.name === example);
  if (!e) throw new ToolError(`No example "${example}" for ${c.spec.name}. Examples: ${c.examples.map((x) => x.name).join(", ")}`);
  return show(e);
}

// ---- get_component_source -------------------------------------------------

export function getComponentSource(ctx: Context, name: string, file?: string): string {
  const shared = ctx.shared.find((s) => normalize(s.name) === normalize(name));
  const files = shared ? shared.files : findComponent(ctx, name).files;
  const picked = file ? files.filter((f) => f.path === file || f.path.endsWith(`/${file}`)) : files;
  if (!picked.length) throw new ToolError(`No file "${file}" in ${name}. Files: ${files.map((f) => f.path).join(", ")}`);
  return picked
    .map((f) => {
      const lang = f.path.endsWith(".css") ? "css" : f.path.endsWith(".tsx") ? "tsx" : "ts";
      return `### ${f.path}\n\n\`\`\`${lang}\n${f.content.trimEnd()}\n\`\`\``;
    })
    .join("\n\n");
}

// ---- get_tokens -----------------------------------------------------------

export function getTokens(ctx: Context, prefix?: string): string {
  const p = prefix?.trim().replace(/^--[a-z]+-/, "").replace(/-/g, ".");
  const tokens = p ? ctx.tokens.filter((t) => t.path.startsWith(p)) : ctx.tokens;
  if (!tokens.length) throw new ToolError(`No tokens start with "${prefix}". Try: color, color.action, radius, space.`);
  return [
    `Semantic tokens as CSS variables. Use these, not raw colors: they switch for dark mode automatically (\`prefers-color-scheme\`, or \`data-theme="light|dark"\` on <html>). With Tailwind v4, write e.g. \`bg-(${tokens[0].cssVar})\`.`,
    "",
    "| Token | CSS variable | Light | Dark |",
    "|---|---|---|---|",
    ...tokens.map((t) => `| ${t.path} | \`${t.cssVar}\` | ${t.light} | ${t.dark} |`),
  ].join("\n");
}

// ---- validate_props -------------------------------------------------------

/** Props every component takes through React / React Aria, which specs don't list. */
const PASSTHROUGH = /^(className|style|id|key|ref|slot|children|aria-.+|data-.+|on[A-Z]\w*)$/;

export function validateProps(ctx: Context, name: string, props: Record<string, unknown>): string {
  const c = findComponent(ctx, name);
  const errors: string[] = [];
  const notes: string[] = [];

  for (const [n, p] of Object.entries(c.spec.props)) {
    if (p.required && !(n in props)) {
      if (n === "children" && typeof props["aria-label"] === "string") continue;
      errors.push(`Missing required prop \`${n}\`: ${p.description}`);
    }
  }

  for (const [n, value] of Object.entries(props)) {
    const p = c.spec.props[n];
    if (!p) {
      if (!PASSTHROUGH.test(n)) notes.push(`\`${n}\` isn't in the spec. It may still be a valid React Aria prop; check with get_component.`);
      continue;
    }
    if (p.type === "enum" && !(p.values ?? []).includes(String(value))) {
      errors.push(`\`${n}\`: ${JSON.stringify(value)} isn't allowed. Use one of ${(p.values ?? []).map((v) => `"${v}"`).join(", ")}.`);
    }
    if (p.type === "boolean" && typeof value !== "boolean") errors.push(`\`${n}\` must be a boolean.`);
    if (p.type === "number" && typeof value !== "number") errors.push(`\`${n}\` must be a number.`);
    if (p.type === "string" && typeof value !== "string") errors.push(`\`${n}\` must be a string.`);
  }

  if (props.isInvalid === false) {
    notes.push("`isInvalid={false}` takes over validity and hides built-in errors (required, validate). Leave isInvalid out unless the app itself found an error.");
  }

  if (!errors.length && !notes.length) return `✓ These props are valid for ${c.spec.name}.`;
  return [
    errors.length ? `✗ ${errors.length} problem${errors.length > 1 ? "s" : ""} with ${c.spec.name}:\n${bullets(errors)}` : `✓ No errors for ${c.spec.name}.`,
    notes.length ? `\nNotes:\n${bullets(notes)}` : "",
    c.spec.a11y.requirements?.length ? `\nAlso check the accessibility requirements, which props alone can't prove:\n${bullets(c.spec.a11y.requirements)}` : "",
  ].join("\n");
}

// ---- get_setup ------------------------------------------------------------

export function getSetup(ctx: Context): string {
  const n = ctx.brand.name;
  return `# Setting up ${ctx.brand.displayName}

${ctx.brand.displayName} copies component source into the project and keeps it upgradable with a three-way merge.

1. \`npx ${n} init\` writes rdloom.json, copies the tokens CSS (default \`src/styles/rdloom-tokens.css\`) and shared utils.
2. Import the tokens CSS once, in the app's main stylesheet or entry file.
3. Make sure Tailwind v4 scans the components directory (default \`src/components/rdloom\`).
4. \`npx ${n} add <id> [...] --install\` adds components and installs their npm packages. \`npx ${n} list\` shows them.
5. Commit rdloom.json, rdloom.lock.json and .rdloom/ (the merge base for upgrades).

Components from GitHub registries (public or private): \`npx ${n} add owner/repo/item\`, \`owner/repo/item#tag\`, or \`@ns/item\` with "registries": { "@ns": "owner/repo" } in rdloom.json. Private repos need GH_TOKEN or \`gh auth login\`.

Later: \`npx ${n} diff\` shows local vs upstream changes; \`npx ${n} upgrade\` merges upstream changes into edited files (conflicts get git-style markers and exit code 1).

Requires React 19. Behavior and accessibility come from React Aria Components, so keep its props (\`isDisabled\`, \`onPress\`, \`onSelectionChange\`...) rather than DOM ones (\`disabled\`, \`onClick\`, \`onChange\`).`;
}
